baseURL = 'https://manueldemiguel.github.io/trabajo/'
languageCode = 'en-us'
title = 'My New Hugo Site'
defaultContentLanguage="es"

theme = 'relearn'


[params]
    themeVariant ="neon"

[[menu.shortcuts]]
name="<i class='fab fa-github-square'></i>   GitHub"
identified=""
url="https://github.com/ManuelDeMiguel/"
weight=1

[[menu.shortcuts]]
name="<i class='fab fa-youtube'></i>   YouTube"
identified=""
url="https://www.youtube.com/channel/UCFi-GsWr3DoDIvfGveFljsA"
weight=2

[[menu.shortcuts]]
name="<i class='fas fa-graduation-cap'></i>   Instituto"
identified=""
url="https://cpilosenlaces.com/"
weight=3


[Languages]
    [Languages.es]
        title = "Ejemplo para el uso de idiomas"
        weight = 1
        languageName = "Español"
        contentDir = "content/es"
    [Languages.en]
        title = "Example use language"
        weight = 2
        languageName = "English"
        contentDir = "content/en"
   [Languages.fr]
        title = "Exemple d'utilisation des langues"
        weight = 3
        languageName = "Français"
        contentDir = "content/fr"